In [2]:
from scipy.spatial.distance import cdist 
import torch 

In [33]:
a = torch.eye((2))
b = torch.tensor([[0,1],[1,0]])

In [34]:
a, b

(tensor([[1., 0.],
         [0., 1.]]),
 tensor([[0, 1],
         [1, 0]]))

In [35]:
cdist(a, b, "euclidean")

array([[1.41421356, 0.        ],
       [0.        , 1.41421356]])